### ISSUE TITLE
OIDC authorisation failed

### ISSUE THREAD

**Issue by ronrem** [ansibleguy76/ansibleforms#242]
**Describe the bug**
OIDC authentication is successful but authorisation fails. Guide followed: https://github.com/ansibleguy76/ansibleforms/pull/178

My OIDC config:
```
{
    "status": "success",
    "message": "OIDC found",
    "data": {
        "output": {
            "issuer": "http://keycloak:8080/realms/teams",
            "client_id": "ansibleforms",
            "secret_id": "2a8IIjQIPK6ws391nfMWTjtArj5dMW8b",
            "enabled": 1,
            "groupfilter": "^default"
        },
        "error": ""
    }
}
```

Server is giving the following error:
```
2024-11-20 15:17:26:1726 error: [ansibleforms] Query error : Error: Column 'username' cannot be null
An uncaught exception happened, ignore...  Error: Column 'username' cannot be null
    at PromiseConnection.query (/app/dist/node_modules/mysql2/promise.js:94:22)
    at Object.MySql.do (/app/dist/src/models/db.model.js:24:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sql: "INSERT INTO AnsibleForms.`tokens` set `username` = NULL, `username_type` = 'oidc', `refresh_token` = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Imdyb3VwcyI6W10sInR5cGUiOiJvaWRjIiwicm9sZXMiOlsicHVibGljIl19LCJyZWZyZXNoIjp0cnVlLCJpYXQiOjE3MzIxMTU4NDYsImV4cCI6MTczMjIwMjI0Nn0.CuTSODXnhvO-KPKArXNJS4p6h_iCjXV6BXqk3lTyWwk'",
  sqlState: '23000',
  sqlMessage: "Column 'username' cannot be null"
}
```

The "about me" is giving type: "oidc", roles: "public", no username and no groups. See image attached below.

**To Reproduce**

**Expected behavior**
Groups from Keycloak are available in AnsibleForms role(s).

```
roles:
  - name: default-roles-teams
    groups: 
      - oidc/default-roles-teams
```

Keycloak group information is returned, mapper config is correctly set:

```
{
  "exp": 1732114222,
  "iat": 1732113922,
  "auth_time": 1732113922,
  "jti": "fee67cdc-de52-4c09-8e84-a0ac49716684",
  "iss": "http://keycloak:8080/realms/teams",
  "aud": "account",
  "sub": "3306d9fa-ac8e-49f8-9822-e84d8bf803de",
  "typ": "Bearer",
  "azp": "ansibleforms",
  "sid": "be93f9f3-d9d8-41f2-8a9f-655a179debd8",
  "acr": "1",
  "allowed-origins": [
    ""
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-teams"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email",
  "email_verified": false,
  "name": "***",
  "groups": [
    "offline_access",
    "uma_authorization",
    "default-roles-teams"
  ],
  "preferred_username": "***",
  "given_name": "***",
  "family_name": "***",
  "email": "***"
}
```

**Screenshots**

**Version**
ansibleforms v4.0.4/4.0.7
keycloak v24.0.4/26.0.5 

**Deployment**
Deployed ansibleforms with :
- kubernetes

**Additional context**
![image](https://github.com/user-attachments/assets/5e398de9-5fa8-4419-b598-9227c77637cd)

**Comment by ansibleguy76** [comment]
This was originally designed on request.
At that time the username was passed a part of the payload


```
const extractOidcUser = async function(payload, groups) {
  return {
    username: payload.preferred_username,
    groups: groups.map(g => `oidc/${g}`)
  }
};
```

I'm not familiar with OIDC in detail.  is the preferred_username not a required or standard property to pass ?

**Comment by ansibleguy76** [comment]
preferred_username | String | The primary username that represents the user. It could be an email address, phone number, or a generic username without a specified format. Its value is mutable and might change over time. Since it's mutable, this value can't be used to make authorization decisions. It can be used for username hints and in human-readable UI as a username. The profile scope is required to receive this claim. Present only in v2.0 tokens.

From what I read online, the preferred_username property is indeed the username that needs be passed.  My code blindly assumes this is passed.  I could throw an error saying the property is not passed.   I'll wait for you feedback first.

**Comment by ansibleguy76** [comment]
I'll close this, awaiting for feedback.  Reopen if you believe something needs to change (username property...)
